/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.GroupHelper;
import edu.neu.csye6200.model.Group;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erruc
 */
public class ClassroomUI extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    List<Group> grouplist;
    String classroomId, groupId,groupCount,studentCount,teacherAssigned;
    public ClassroomUI() {
        initComponents();
        jTableClassroomInfo.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableClassroomInfo.setAutoCreateColumnsFromModel(true);
        try {
        	System.out.println("Showing Class romm and group info:");
        	fetchClassRoomGroupInfo((DefaultTableModel)jTableClassroomInfo.getModel())
        	.addRow(new Object[]{classroomId,groupId,groupCount,studentCount,teacherAssigned});
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
     public ClassroomUI(List<Group> grouplist) {
        initComponents();
        jTableClassroomInfo.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableClassroomInfo.setAutoCreateColumnsFromModel(true);

        DefaultTableModel model = (javax.swing.table.DefaultTableModel)jTableClassroomInfo.getModel(); 
        System.out.println("Showing Class romm and group info:");
        try {
        	fetchClassRoomGroupInfo(model);
		} catch (Exception e) {
			e.printStackTrace();
		}
        model.addRow(new Object[]{groupId, classroomId, teacherAssigned, studentCount});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelClassroomtitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClassroomInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1456, 587));
        setPreferredSize(new java.awt.Dimension(1456, 587));

        jPanel2.setBackground(new java.awt.Color(178, 255, 176));
        jPanel2.setPreferredSize(new java.awt.Dimension(1456, 70));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jLabelClassroomtitle.setBackground(new java.awt.Color(178, 255, 176));
        jLabelClassroomtitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelClassroomtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClassroomtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/classroom1.PNG"))); // NOI18N
        jLabelClassroomtitle.setText("Classroom Info");
        jLabelClassroomtitle.setToolTipText("");
        jLabelClassroomtitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lmdic1.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(355, 355, 355)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClassroomtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(618, 618, 618))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelClassroomtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jInternalFrame1.setResizable(true);
        jInternalFrame1.setFrameIcon(null);
        jInternalFrame1.setVisible(true);

        jTableClassroomInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                 "Group Id", "Classroom Id ", "No. of  Students ", "Teacher Assigned"
            }
        ));
        jTableClassroomInfo.setPreferredSize(new java.awt.Dimension(468, 442));
        jScrollPane1.setViewportView(jTableClassroomInfo);

        jInternalFrame1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassroomUI().setVisible(true);
            }
        });
    }
    
    private DefaultTableModel fetchClassRoomGroupInfo(DefaultTableModel model) throws Exception {

        //JTableHeader th = new JTableHeader();
        
        model.setRowCount(0);
        GroupHelper helper = new GroupHelper();
        List<Group>	 groups = helper.getClassRoomGroupInfo();
        for (Group group : groups) {
            System.out.println(group.getGroupId());
            Object[] row = new Object[4];
            row[0] = group.getGroupId();
            row[1] = group.getClassId();
            row[3] = group.getTeacherId();
            row[2] = group.getStudentsEnrolled();
            model.addRow(row);

        }
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClassroomtitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClassroomInfo;
    // End of variables declaration//GEN-END:variables
}
