/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.FeedbackService;
import edu.neu.csye6200.controller.GroupHelper;
import edu.neu.csye6200.model.Classroom;
import edu.neu.csye6200.model.Feedback;
import edu.neu.csye6200.model.Group;
import edu.neu.csye6200.model.Teacher;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author erruc
 */
public class LMDLandingPage extends javax.swing.JFrame {
    private TeacherUI teacher;
    private StudentUI student;
    private  ClassroomUI classroom;
    private FeedbackUI feedback;
    /**
     * Creates new form MainPage
     */
    public LMDLandingPage() {
        initComponents();
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTopPanel1 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelLeftPane = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPaneUsers = new org.jdesktop.swingx.JXTaskPane();
        jLabelTeachers = new javax.swing.JLabel();
        jLabelStudents = new javax.swing.JLabel();
        jXTaskPaneNotifications = new org.jdesktop.swingx.JXTaskPane();
        jReminderLabel = new javax.swing.JLabel();
        jXTaskPaneInfrastructure = new org.jdesktop.swingx.JXTaskPane();
        jLabelClassrooms = new javax.swing.JLabel();
        jLabelViewFeedback = new javax.swing.JLabel();
        jRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTopPanel1.setBackground(new java.awt.Color(178, 255, 176));
        jTopPanel1.setMaximumSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setMinimumSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setPreferredSize(new java.awt.Dimension(200, 80));
        jTopPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_menu_48px_1.png"))); // NOI18N
        jTopPanel1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 46, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Hello, Admin");
        jLabel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel4ComponentShown(evt);
            }
        });
        jTopPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1151, 0, 151, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lmd3.PNG"))); // NOI18N
        jTopPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lmd11.PNG"))); // NOI18N
        jTopPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 390, 40));

        getContentPane().add(jTopPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        jSplitPanel.setLayout(new java.awt.BorderLayout());

        jPanelLeftPane.setMaximumSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setMinimumSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setPreferredSize(new java.awt.Dimension(300, 495));
        jPanelLeftPane.setLayout(new java.awt.BorderLayout());

        jXTaskPaneContainer1.setBackground(new java.awt.Color(178, 255, 176));
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer1.setLayout(verticalLayout1);

        jXTaskPaneUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.PNG"))); // NOI18N
        jXTaskPaneUsers.setTitle("Users");
        jXTaskPaneUsers.setAlignmentY(10.0F);
        jXTaskPaneUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXTaskPaneUsers.setPreferredSize(new java.awt.Dimension(95, 120));

        jLabelTeachers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTeachers.setText("Teachers");
        jLabelTeachers.setPreferredSize(new java.awt.Dimension(90, 30));
        jLabelTeachers.setRequestFocusEnabled(false);
        jLabelTeachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTeachersMouseClicked(evt);
            }
        });
        jXTaskPaneUsers.getContentPane().add(jLabelTeachers);

        jLabelStudents.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStudents.setText("Students");
        jLabelStudents.setPreferredSize(new java.awt.Dimension(90, 30));
        jLabelStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStudentsMouseClicked(evt);
            }
        });
        jXTaskPaneUsers.getContentPane().add(jLabelStudents);

        jXTaskPaneContainer1.add(jXTaskPaneUsers);

        jXTaskPaneNotifications.setBackground(new java.awt.Color(204, 245, 217));
        jXTaskPaneNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bell3.PNG"))); // NOI18N
        jXTaskPaneNotifications.setScrollOnExpand(true);
        jXTaskPaneNotifications.setTitle("Notifications");
        jXTaskPaneNotifications.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXTaskPaneNotifications.setPreferredSize(new java.awt.Dimension(143, 120));

        jReminderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jReminderLabel.setForeground(new java.awt.Color(51, 51, 51));
        jReminderLabel.setText("Reminder");
        jReminderLabel.setAlignmentY(5.0F);
        jReminderLabel.setIconTextGap(10);
        jReminderLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        jReminderLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        jReminderLabel.setRequestFocusEnabled(false);
        jXTaskPaneNotifications.getContentPane().add(jReminderLabel);

        jXTaskPaneContainer1.add(jXTaskPaneNotifications);

        jXTaskPaneInfrastructure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infra1.jpg"))); // NOI18N
        jXTaskPaneInfrastructure.setTitle("Infrastructure");
        jXTaskPaneInfrastructure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXTaskPaneInfrastructure.setPreferredSize(new java.awt.Dimension(153, 120));

        jLabelClassrooms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClassrooms.setText("Classrooms");
        jLabelClassrooms.setPreferredSize(new java.awt.Dimension(90, 30));
        jLabelClassrooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClassroomsMouseClicked(evt);
            }
        });
        jXTaskPaneInfrastructure.getContentPane().add(jLabelClassrooms);

        jLabelViewFeedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelViewFeedback.setText("View Feeback");
        jLabelViewFeedback.setPreferredSize(new java.awt.Dimension(90, 30));
        jLabelViewFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewFeedbackMouseClicked(evt);
            }
        });
        jXTaskPaneInfrastructure.getContentPane().add(jLabelViewFeedback);

        jXTaskPaneContainer1.add(jXTaskPaneInfrastructure);

        jPanelLeftPane.add(jXTaskPaneContainer1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanelLeftPane);

        jRightPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jRightPanel);

        jSplitPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jSplitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1320, 990));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStudentsMouseClicked
        // TODO add your handling code here:
       student= new StudentUI();
       student.setVisible(true);
     
     //  jRightPanel.setRightComponent(student);

       
    }//GEN-LAST:event_jLabelStudentsMouseClicked

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jLabelTeachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTeachersMouseClicked
        // TODO add your handling code here:
        teacher= new TeacherUI();
        teacher.setVisible(true);
    }//GEN-LAST:event_jLabelTeachersMouseClicked

    private void jLabelClassroomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassroomsMouseClicked
        try {
            // TODO add your handling code here:
        	try {
        		System.out.println("Calling to create groups and classroom");
        		GroupHelper.groupMe();
        	} catch (Exception e) {
        		e.printStackTrace();
        	}
            GroupHelper helper= new GroupHelper();
           List<Group> grouplist=helper.getClassRoomGroupInfo();
           //ClassroomUI classUI= new ClassroomUI(grouplist);
           classroom = new ClassroomUI(grouplist);
           //classUI.setVisible(true);
           classroom.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(LMDLandingPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelClassroomsMouseClicked

    private void jLabelViewFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewFeedbackMouseClicked
        // TODO add your handling code here:
       
       Feedback fd= new Feedback();
       FeedbackService fdservice= new FeedbackService();
       List<Feedback> fdlist= new ArrayList<Feedback>();
        try {
            fdlist=fdservice.getAllTeacherReviews();
         //   fdservice.
        } catch (Exception ex) {
            Logger.getLogger(LMDLandingPage.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       feedback= new FeedbackUI(fdlist);
       feedback.setVisible(true);
    }//GEN-LAST:event_jLabelViewFeedbackMouseClicked

    private void jLabel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel4ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel4ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LMDLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMDLandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClassrooms;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelStudents;
    private javax.swing.JLabel jLabelTeachers;
    private javax.swing.JLabel jLabelViewFeedback;
    private javax.swing.JPanel jPanelLeftPane;
    private javax.swing.JLabel jReminderLabel;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jSplitPanel;
    private javax.swing.JPanel jTopPanel1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneInfrastructure;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneNotifications;
    private org.jdesktop.swingx.JXTaskPane jXTaskPaneUsers;
    // End of variables declaration//GEN-END:variables
}
